language: python

python:
  - '2.7'

branches:
  only:
    - master

sudo: false

cache:
  directories:
  - $HOME/build/cosmicpy/cosmicpy/build/extern
  - $HOME/build/cosmicpy/cosmicpy/build/GSL
  - $HOME/build/cosmicpy/cosmicpy/build/Boost

env:
  global:
  - OMP_NUM_THREADS 8
  - secure: PK7hooC3B0me1ABWfR7oUy6np/G0GorCGih00l87hc6AXuYFS347O0UCH2g5mlaEo5AS/R8S8CWU9pA+LFBmbqqg5Em3vg/NvXhuMHq8UgwoQBfIj+l2n1bSO4+7Vz2YwP7oUGPl4t1ACVVgQEGnt9Cp7xDjUoe3VVO5bzpu89s=

before_install:
  - openssl aes-256-cbc -K $encrypted_cb2a50c2b05b_key -iv $encrypted_cb2a50c2b05b_iv -in .travis.key.enc -out id_rsa_travis.enc -d
  - openssl rsa -in id_rsa_travis.enc -out id_rsa_travis -passin pass:$DEPLOY_KEY_SECRET
  - chmod 600 id_rsa_travis
  - eval `ssh-agent -s`
  - ssh-add ./id_rsa_travis
  - chmod 755 ./.deploy_doc.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  - source activate test-environment
  - conda install --yes numpy=1.9 scipy matplotlib Sphinx=1.2.2 Pygments ipython
  - pip install sphinx-bootstrap-theme sphinxcontrib-napoleon sphinxcontrib-bibtex
  - python setup.py build

script:
  - (cd doc; travis_wait make html)

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./.deploy_doc.sh || false'
